### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dmpop** [mehdilauters/digikamWebUi#1]
Followed the installation instructions, and almost managed to get digiKamWebUi up and running on Ubuntu 14.04. But the interface looks below. I can't figure out what the problem is.

![screenshot-localhost 2014-10-16 19-11-23](https://cloud.githubusercontent.com/assets/837588/4667064/52157642-5559-11e4-8031-6ed849c22ad9.png)

**Comment by mehdilauters** [comment]
You're almost done!
What you see are debug messages. To disable them, change tje debug level
"To activate debug informations, reasons of 500 errors, warnings... Please set Configure::write('debug', **0**); to 2 in **app/config/core.php**"
2 is debug, 0 is production.

Just before that, you should try to download an image as i guess you have a path issue (no thumbnails).
Rigth click on an image icon, "display picture" or "copy image location" then paste in the address bar.
You will probably see errors about file that does not exists. 
You can check the digikam root path into **app/Config/bootstrap.php** 
Configure::write('Digikam.root', '**/home**');
 which will be prepended to the **AlbumRoot.specificPath** from digikam database.
thanks, I will update the doc

**Comment by dmpop** [comment]
Thank you so much for your prompt reply! I'm not sure what the correct path in `Configure::write('Digikam.root', '/home');` should be. My photos are stored in the `/home/user/Photos/` directory (the _digikam4.db_, _thumbnails-digikam.db_, and _digikamWebUi.db_ are also stored in this directory). digiKamWebUi seems like a great app, and I really want to make it work.

**Comment by mehdilauters** [comment]
I don't know what should be on your Digikam.root. it's depending on which path is in AlbumRoot.specificPath.
Path are built as below

Configure::read('**Digikam.root**') / AlbumRoot.**specificPath** / Album.**relativePath** / Image.**name**
so for me for example it was
"/home" / "user/private/Photos" /  "myAlbum" / "myImage_1.jpg"

You can check values from the database by opening the digikam4.db with sqlitebrowser.
Thanks, I hope it will finally work. But it is not well finished there is still some work to do...

**Comment by dmpop** [comment]
In my case, the value of the _specificPath_ field in the _AlbumRoots_ table of the  _digikam4.db_ database is _/home/dmpop/Photos_. So theoretically, it should be `Configure::write('Digikam.root', ' ');` But this doesn't work.

**Comment by mehdilauters** [comment]
You have a blank space I guess that could be the problem. It should be Configure::write('Digikam.root', '');
If this still doesn't work, you can check the app/tmp/log/ error.log or debug.log to really check the error text

**Comment by dmpop** [comment]
Removing the blank space didn't help either. Here is a snip from the _error.log_:

`2014-10-16 21:15:20 Error: [InternalErrorException] Internal Server Error
Request URL: /digikamWebUi/images/download/92/big
Stack Trace:
#0 /var/www/html/digikamWebUi/lib/Cake/Error/ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/html/d...', 421)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/html/d...', 421, Array)
#2 /var/www/html/digikamWebUi/lib/Cake/Core/App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/html/d...', 421, Array)
#3 /var/www/html/digikamWebUi/lib/Cake/Core/App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}`

And here is a snip from _debug.log_:

`
2014-10-16 20:53:47 Notice: Notice (8): Undefined index: AlbumRoot in [/var/www/html/digikamWebUi/app/Model/AlbumRoot.php, line 68]
Trace:
AlbumRoot::getPath() - APP/Model/AlbumRoot.php, line 68
Album::getPath() - APP/Model/Album.php, line 100
Image::getPath() - APP/Model/Image.php, line 240
ImagesController::download() - APP/Controller/ImagesController.php, line 597
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 486
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 187
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 162
[main] - APP/webroot/index.php, line 109
`

**Comment by mehdilauters** [comment]
That's strange...
please add the following line in /var/www/html/digikamWebUi/app/Model/AlbumRoot.php line 69 and check 
debug($data);
It should write to your debug.log the content of your database AlbumRoot. Maybe it will help you.
Then you can do the same in app/Model/Album::getPath and app/Model/Image::getPath
And you can print them within the browser by setting debug to 2 in Config/core.php

**Comment by dmpop** [comment]
Adding `debug($data);` changes nothing: there is no additional info in _debug.log_.
