### ISSUE TITLE
Correct path to sqlite schema in installation guide

### ISSUE THREAD

**Issue by r0max** [mehdilauters/digikamWebUi#2]
The path to the digikamWebUi schema in the installation guide is incorrect. It should state

```
./app/Config/Schema/digikamWebUi.sql
```

instead of 

```
./app/Model/Datasource/digikamWebUi.sql
```

The latter file also exists and is 0 bytes long, and could be removed.

You could also add how to create the sqlite db file

```
cat app/Config/Schema/digikamWebUi.sql | sqlite3 digikamWebUi.db
```

Just trying your application now, will let you know any more findings.

Regards

**Comment by mehdilauters** [comment]
Thanks for your review. I updated the documentation!

Regards

Mehdi
